### ISSUE TITLE
Add support for the C extension

### ISSUE THREAD

**Issue by emberian** [SRI-CSL/l3riscv#1]
This would require designing variable-length instruction decoding. I propose `Decode16`, `Decode32`, etc. I also propose extending F_Result to contain `half list`, with `rawReadInst` including a simple state machine which pulls off additional parcels from `MEM` as necessary based on the instruction length. Care will be needed to update things like "PC + 4" for branches etc. I propose `declare instLen :: bit(8)`, which indicates the length (in bytes) of the currently executing instruction, and using that instead of the hardcoded 4.

Support for this (and other) extensions should probably be conditional? In that, there would be a `declare enableC :: bool` that would (probably!) be constant for any system, and which all semantics-changing C things are conditional on. This would make it easier to verify I-only programs against these semantics, for example. (Otherwise, some invalid instructions or misaligned accesses might be missed).

**Comment by emberian** [comment]
Let me know what you think of this approach, as I'd like to implement it.

**Comment by pmundkur** [comment]
I haven't examined the C extension very closely, but this sounds reasonable.
Ideally, C support would be conditional on the C bit of misa, but checking that on every instruction would be slow.  Writes to misa could be intercepted like CSRs writes are currently intercepted, and the global enableC set appropriately; this would allow only checking enableC in fetcher/decoder.
Virtualization also needs consideration, but perhaps that portion of the spec is not fleshed out yet.

**Comment by pmundkur** [comment]
mostly done, except for changing misa.c.
